name: Greetings

on: 
  push:
  pull_request:
  workflow_dispatch:
  

jobs:
  greeting:
    runs-on: imac
    
    permissions:
      issues: write
      pull-requests: write
      
    steps:
    - name: Trust Workspace Directory
      run: git config --global --add safe.directory "${{ github.workspace }}"
  
    - name: Checkout
      uses: actions/checkout@v6
      with:
        chown: false

    - name: Run Command
      shell: bash -l {0}
      env:
        REPO_INFO: ${{ github.repository }}
      run: |
        #!/usr/bin/env bash

        set -eou pipefail

        echo "${REPO_INFO}"

    - uses: actions/first-interaction@v1
      if: github.event_name == 'pull_request'
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
